[tool.poetry]
name = "eskiz-sms"
version = "0.1.11"
description = "Package for eskiz.uz/sms"
homepage = "https://github.com/malikovss/eskiz-sms"
authors = ["Malikov <oopanndaa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.26.0"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
